# Usamos una imagen oficial de Node.js
FROM node:20-alpine

# Establecemos el directorio de trabajo
WORKDIR /app/website

# Copiamos los archivos de dependencias
COPY package.json package-lock.json ./

# Instalamos las dependencias de Node
RUN npm install

# Copiamos el resto de los archivos de la web
COPY . .

# Exponemos el puerto de Docusaurus (por defecto 3000)
EXPOSE 3000

# Comando para iniciar el servidor de desarrollo del frontend
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]